version: "3"
services:
  # postgres:
  #   image: postgres:11
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  fastapi:
    build: .
    volumes:
      - ./source/backend:/code/app:z
    command: uvicorn app.server:app --port 8000 --host 0.0.0.0 --reload
    ports:
      - 8000:8000
    # depends_on:
    #   - postgres
